import Head from "next/head";
import { BannerParallax } from "../components";
import { Section1, Section2, Section3 } from "../components/pages";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BannerParallax heading="We achieve Breakthroughs for you" />
        <Section1 />
        <br />
        <br />
        <Section2 />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <Section3 />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </main>
    </div>
  );
}
